# Generated by Django 4.0.3 on 2022-09-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('actor_name', models.CharField(max_length=30)),
                ('actress_name', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('director_name', models.CharField(max_length=30)),
            ],
        ),
    ]
